# Generated by Django 5.1.1 on 2024-10-20 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name_plural': 'locales/Negocios'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'ordenes'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'productos'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'perfiles'},
        ),
    ]
